FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Verificare debug temporară
RUN ls -la dist/

EXPOSE 8080
ENV PORT=8080

CMD ["node", "dist/main"]
